services:
  web:
    build: .
    image: myapp:v22
    ports:
      - "9012:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/db
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres